# site setting
title: podondra site
email: ondrej.podsztavek@gmail.com
description: my personal site
baseurl: ""
url: "https://podondra.cz"
github_username: podondra

# build setting
exclude: [CNAME, LICENSE, README.md]
